### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Eunoia1729** [opencodeiiita/Competitive_Coding#16]
Week 1, Issue 3: Find and fix the runtime error(s) by modifying/adding not more than 1 line.

**Comment by akshit129** [comment]
@opencodebot claim

**Comment by Tarunasudani** [comment]
@opencodebot claim

**Comment by Jahanvi21** [comment]
@opencodebot claim

**Comment by Eunoia1729** [comment]
@Jahanvi21 
You can start working on the issue. This issue is open to everyone so no need to claim. :)

**Comment by agamjotpanesar** [comment]
@opencodebot claim

**Comment by Eunoia1729** [comment]
> @opencodebot claim

@agamjotpanesar  You can start working on the issue. This issue is open to everyone so no need to claim. :)

**Comment by ak0005** [comment]
@opencodebot claim

**Comment by Eunoia1729** [comment]
#35 had the first correct fix
