### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Eunoia1729** [opencodeiiita/Competitive_Coding#24]
Week 1, Issue 5: This issue is a bit different as "two" lines have to be changed. Both the erroneous lines are compilation errors. 30 points will only be awarded when the PR has the correct fixes for both the lines. No partial points will be awarded.

**Comment by ThunderrZero** [comment]
@opencodebot claim

**Comment by naman-150200** [comment]
@opencodebot claim

**Comment by ak0005** [comment]
@opencodebot claim

**Comment by ak0005** [comment]
@opencodebot claim

**Comment by Eunoia1729** [comment]
#25 has debugged as per #24 's requirements.
