### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by Eunoia1729** [opencodeiiita/Competitive_Coding#6]
Week 1, Issue 2: Find and fix the syntax error(s) by modifying/adding not more than 1 line.

**Comment by brownsands** [comment]
can i work on this issue!!

**Comment by ashish4321** [comment]
@brownsands no need to claim. Just craete a PR. The first correct PR will be merged

**Comment by Eunoia1729** [comment]
#10 was the quickest correct PR !
